-- Ability summary generated by MiMo at end of project (能力档案)
-- Manually applied via SQL in production; this file documents the schema.

create table if not exists public.simulation_ai_summaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  user_simulation_id uuid not null unique,
  model text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.simulation_ai_summaries enable row level security;

drop policy if exists "own ai summary read" on public.simulation_ai_summaries;
create policy "own ai summary read"
  on public.simulation_ai_summaries
  for select
  using (auth.uid() = user_id);

create index if not exists simulation_ai_summaries_user_sim_idx
  on public.simulation_ai_summaries (user_simulation_id);
